language: python

python:
    - "3.6"


install:
    # Install conda
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda

    # Install dependencies
    - conda env create -n dl -f environment.yml
    - source activate dl

    # Install testing dependencies
    - conda install pathlib nbconvert nbformat jupyter_client ipykernel

script:
    - python $TRAVIS_BUILD_DIR/.tests/nbrun.py

notifications:
  email: false
